# Generated by Django 3.1.5 on 2021-06-07 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_processo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CadastroProcesso',
            new_name='Planilha',
        ),
    ]
