# Generated by Django 3.1.5 on 2021-06-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasta', models.CharField(max_length=100, verbose_name='Pasta')),
                ('comarca', models.CharField(max_length=100, verbose_name='Comarca')),
                ('uf', models.CharField(max_length=100, verbose_name='UF')),
            ],
        ),
    ]
